### ISSUE TITLE
API reference link

### ISSUE THREAD

**Issue by chriskuech** [Azure/azure-storage-js#13]
I see you support Swagger, but I don't see where the generated API reference is located.  Please put a link to the API reference in the README if it exists.

**Comment by XiaoningLiu** [comment]
@chriskuech Yes, the API document is under generation by docs team, will update a link after it is ready.

**Comment by seguler** [comment]
Here is the API reference link: https://docs.microsoft.com/en-us/javascript/api/%40azure/storage-blob/?view=azure-node-preview

**Comment by XiaoningLiu** [comment]
API reference link is already available in readme and GitHub repo description. Thanks!
