### ISSUE TITLE
Browser func - uploadBrowserDatatoBlockBlob: TypeError: blockBlobURL.upload is not a function

### ISSUE THREAD

**Issue by bearcanrun** [Azure/azure-storage-js#18]
### Which service(blob, file, queue, table) does this issue concern?
blob

### Which version of the SDK was used?
10.0.0-preview

### What's the Node.js/Browser version?
Browser

### What problem was encountered?
When attempting to upload a file from the browser using function uploadBrowserDatatoBlockBlob() I receive  a TypeError: blockBlobURL.upload is not a function.

This is using the pre-minified azure-storage.blob.min.js provided in the latest v10 preview release.

The function is supplied with required parameters as shown by console logging before invoking the function:
![screenshot-2018-09-19-10 01 07](https://user-images.githubusercontent.com/361344/45769883-bc940900-bbf5-11e8-86bf-6f3307230fcf.png)

I've received the same TypeError before when accidentally using a node only function on the browser. I attempted to use blockBlobURL.upload directly and received the same error. 

### Steps to reproduce the issue?
My code is pulled directly from the [highlevel sample](https://github.com/Azure/azure-storage-js/blob/master/blob/samples/highlevel.sample.ts) 

I notice the browser functions are commented out, so they may not be working yet. 

Also, does my pipeline need something defined for httpClient parameter? I haven't found any clear documentation on this. 

### Have you found a mitigation/solution?
No mitigation/solution found yet.

**Comment by XiaoningLiu** [comment]
@bearcanrun 

The browser functions are commented out because we cannot run both Node.js and browser functions within one file, so commented out them.

Can you share your full source code?

Or you can try following simple code:

**Comment by bearcanrun** [comment]
Thank you! I somehow overlooked the BlockBlobURL vs BlobURL. My final working code is:

```
import * as Azure from '@azure/storage-blob'

async saveImage (sasURL, containerName, imgBlob) {
    const pipeline = Azure.StorageURL.newPipeline(new Azure.AnonymousCredential())
    const serviceURL = new Azure.ServiceURL(sasURL, pipeline)
    const containerURL = Azure.ContainerURL.fromServiceURL(serviceURL, containerName)
    const blockBlobURL = Azure.BlockBlobURL.fromContainerURL(containerURL, fileName)
    const uploadImage = await Azure.uploadBrowserDataToBlockBlob(Azure.Aborter.None, imgBlob, blockBlobURL)
    return uploadImage
  }
```

**Comment by bearcanrun** [comment]
@XiaoningLiu Yes, I'm using it with nodejs backend GraphQL server + frontend React. Main tools are Webpack4, Nodejs, Express, Apollo GraphQL, and React.

**Comment by XiaoningLiu** [comment]
Thanks for sharing : )

We are working on further reducing the bundle size in next release, should largely reducing the frontend bundled js size then.
