### ISSUE TITLE
How to list blobs?

### ISSUE THREAD

**Issue by matijaSos** [Azure/azure-storage-js#19]
I could not find how to list blobs under certain prefix, similar to `listBlobsSegmentedWithPrefix` from the old SDK. I see there is a method for listing the containers, but is there one for listing blobs?

**Comment by XiaoningLiu** [comment]
Hi @matijaSos 

The usage of this SDK is very simple, all convenience APIs are 1:1 mapping to [Azure Storage REST APIs](https://docs.microsoft.com/en-us/rest/api/storageservices/blob-service-rest-api). You can find out all methods provided by following classes.

* `ServiceURL`
* `ContainerURL`
* `BlobURL`
* `BlockBlobURL`
* `AppendBlobURL`
* `PageBlobURL`

If you want to list blobs **under** a container, after getting a `ContainerURL`, call `listBlobFlatSegment` or `listBlobHierarchySegment`

```javascript
const result = await containerURL.listBlobFlatSegment(
      Aborter.None,
      undefined,
      {
        include: [
          ListBlobsIncludeItem.Snapshots,
          ListBlobsIncludeItem.Metadata,
          ListBlobsIncludeItem.Uncommittedblobs,
          ListBlobsIncludeItem.Copy,
          ListBlobsIncludeItem.Deleted
        ],
        maxresults: 1,
        prefix
      }
    );
    assert.ok(result.serviceEndpoint.length > 0);
    assert.ok(containerURL.url.indexOf(result.containerName));
    assert.deepStrictEqual(result.segment.blobItems!.length, 1);
    assert.ok(blobURLs[0].url.indexOf(result.segment.blobItems![0].name));
    assert.deepStrictEqual(result.segment.blobItems![0].metadata, metadata);
```

This SDK provides full typescript definition support, so within IDEs or Editors supporting intelligence, you can find out all methods provided, and all parameter or configs.

![image](https://user-images.githubusercontent.com/6889160/46055793-38ef9480-c180-11e8-81bd-972120de2471.png)

![image](https://user-images.githubusercontent.com/6889160/46055843-75bb8b80-c180-11e8-8544-3aa577d3b293.png)

**Comment by matijaSos** [comment]
Thank you @XiaoningLiu. Also, what is the difference between `listBlobFlatSegment` and `listBlobHierarchySegment`? The docs for them look exactly the same.

**Comment by XiaoningLiu** [comment]
@matijaSos If you do not depend on virtual directory feature, then `listBlobFlatSegment` is your choice.

`listBlobHierarchySegment` has an additional required parameter `delimiter`, which is used in the virtual directory. For example, if you have a blob named "foo/bar", and call `listBlobHierarchySegment` with delimiter set to "/", then "bar" is a blob under the virtual directory "foo".

**Comment by jeyarajcs** [comment]
How to list blobs from virtual directory in latest nodejs SDK?
Example : 
              container_name/videos/May/02/myvideo.webm
              container_name/videos/May/02/myvideo1.webm
              container_name/videos/May/02/myvideo2.webm
              container_name/videos/May/02/myvideo3.webm

I need to get blob list from **container_name/videos/May/02/**
