### ISSUE TITLE
uploadStreamToBlockBlob doesn't work 

### ISSUE THREAD

**Issue by truestep** [Azure/azure-storage-js#23]
### Which service(blob, file, queue, table) does this issue concern?
blob

### Which version of the SDK was used?
Don't know how to find the version of the sdk on Ubuntu.
Here is the output of az cli:
andrey@andrey-ubuntu:~$ az --version
azure-cli (2.0.49)

acr (2.1.7)
acs (2.3.9)
advisor (0.6.0)
ams (0.2.4)
appservice (0.2.5)
backup (1.2.1)
batch (3.4.1)
batchai (0.4.4)
billing (0.2.0)
botservice (0.1.1)
cdn (0.2.0)
cloud (2.1.0)
cognitiveservices (0.2.3)
command-modules-nspkg (2.0.2)
configure (2.0.18)
consumption (0.4.0)
container (0.3.7)
core (2.0.49)
cosmosdb (0.2.2)
dla (0.2.3)
dls (0.1.4)
dms (0.1.1)
eventgrid (0.2.0)
eventhubs (0.3.0)
extension (0.2.2)
feedback (2.1.4)
find (0.2.12)
hdinsight (0.1.0)
interactive (0.3.31)
iot (0.3.3)
iotcentral (0.1.3)
keyvault (2.2.5)
lab (0.1.2)
maps (0.3.2)
monitor (0.2.5)
network (2.2.7)
nspkg (3.0.3)
policyinsights (0.1.0)
profile (2.1.1)
rdbms (0.3.2)
redis (0.3.2)
relay (0.1.2)
reservations (0.4.0)
resource (2.1.5)
role (2.1.8)
search (0.1.1)
servicebus (0.3.1)
servicefabric (0.1.6)
signalr (1.0.0)
sql (2.1.5)
storage (2.2.3)
telemetry (1.0.0)
vm (2.2.6)

Python location '/opt/az/bin/python3'
Extensions directory '/home/andrey/.azure/cliextensions'

Python (Linux) 3.6.5 (default, Oct 18 2018, 19:51:37) 
[GCC 7.3.0]

### What's the Node.js/Browser version?
node 8.10
### What problem was encountered?
uploadStreamToBlockBlob doesn't work 
### Steps to reproduce the issue?
    const buf = Buffer.from([0x62, 0x75, 0x66, 0x66, 0x65, 0x72])
    const bufferStream = new require('stream').PassThrough()
    bufferStream.end(buf)

    const uploadRes = await uploadStreamToBlockBlob(Aborter.none, bufferStream, blockBlobURL, {
      blockSize: 2 * 1024 * 1024, // 2MB block size
      parallelism: 20, // 20 concurrency
       },
      blobHTTPHeaders: { // headers returned with each request to the photo
        blobContentType: "image/jpeg",
        blobCacheControl: `max-age=0, must-revalidate`
      }
    },)

### Have you found a mitigation/solution?
if to save stream to file and use uploadFileToBlockBlob it works

**Comment by vinjiang** [comment]
Please let us know if we can be of any further assistance.
