### ISSUE TITLE
is there the possibility to cancel uploading?

### ISSUE THREAD

**Issue by mrcnw** [Azure/azure-storage-js#24]
that's what is Aborter responsible for?

**Comment by XiaoningLiu** [comment]
@mrcnw Yes.

An aborter instance implements AbortSignal interface, can abort HTTP requests.
- Call `Aborter.none` to create a new Aborter instance without timeout.
- Call `Aborter.timeout()` to create a new Aborter instance with timeout.

For an existing instance aborter:
- Call `aborter.withTimeout()` to create and return a child Aborter instance with timeout.
- Call `aborter.withValue(key, value)` to create and return a child Aborter instance with key/value pair.
- Call `aborter.abort()` to abort current instance and all children instances.
- Call `aborter.getValue(key)` to search and get value with corresponding key from current aborter to all parents.

```javascript
@example
// Abort without timeout
await blockBlobURL.upload(Aborter.none, buf, buf.length);

@example
// Abort container create in 1000ms
await blockBlobURL.upload(Aborter.timeout(1000), buf, buf.length);

@example
// Share aborter cross multiple operations in 30s
// Upload the same data to 2 different data centers at the same time, abort another when any of them is finished
const aborter = Aborter.timeout(30 * 1000);
blockBlobURL1.upload(aborter, buf, buf.length).then(aborter.abort);
blockBlobURL2.upload(aborter, buf, buf.length).then(aborter.abort);

@example
// Cascaded aborting
// All operations can't take more than 30 seconds
const aborter = Aborter.timeout(30 * 1000);
// Following 2 operations can't take more than 25 seconds
await blockBlobURL.upload(aborter.withTimeout(25 * 1000), buf, buf.length);
await blockBlobURL.upload(aborter.withTimeout(25 * 1000), buf, buf.length);
```

**Comment by vinjiang** [comment]
Please let us know if you have further questions.

**Comment by mrcnw** [comment]
Hello again, thanks for answer. I decided to use this lib. Could you tell me how to Abort request on demand (for example on event click)? @XiaoningLiu @vinjiang

**Comment by XiaoningLiu** [comment]
You can manually trigger the abort() of the Aborter instance you hold.

Best,
Xiaoning
