### ISSUE TITLE
SharedKeyCredential function is not importing in browser environment.

### ISSUE THREAD

**Issue by dineshPallapa** [Azure/azure-storage-js#25]
### Which service(blob, file, queue, table) does this issue concern?
blob stroage

### Which version of the SDK was used?
v10.1.0-preview-blob

### What's the Node.js/Browser version?
node -v
 8.4.2
angular 5

### What problem was encountered?
import { SharedKeyCredential, AnonymousCredential, TokenCredential } from "@azure/storage-blob";

SharedKeyCredential is not importing from azure blob other than that all are adding to the project.

### Steps to reproduce the issue?
install the plugin in any Angular project and import in component
import { SharedKeyCredential, Credential, TokenCredential } from "@azure/storage-blob";
ngOnit() {
   console.log(SharedKeyCredential) //undefined
}

ONLY AVAILABLE IN NODE.JS RUNTIME. SharedKeyCredential for account key authorization of Azure Storage service.

Is it possible to use with angularJs 5.

Need help from community.

**Comment by XiaoningLiu** [comment]
Hi @dineshPallapa 

`SharedKeyCredential` is not exported in browser environment for security concerns. We are recommending use SAS or OAuth token for browser auth.

**Comment by dineshPallapa** [comment]
If we need to export in browser environment  how can I do it.

**Comment by XiaoningLiu** [comment]
@dineshPallapa It's not supported in official release. You can use legacy JS SDK https://www.npmjs.com/package/azure-storage with key auth.

**Comment by vinjiang** [comment]
Please let us know if you have further questions.
