### ISSUE TITLE
REQUEST_ABORTED_ERROR when uploading blob

### ISSUE THREAD

**Issue by jakubzloczewski** [Azure/azure-storage-js#38]
### Which service(blob, file, queue, table) does this issue concern?
blob

### Which version of the SDK was used?
"@azure/storage-blob": "10.2.0-preview"

### What's the Node.js/Browser version?
node 8.10
### What problem was encountered?
I've got REQUEST_ABORTED_ERROR when trying to upload blob.
It happens only on azure deployment. On my local machine it works perfectly.

### Steps to reproduce the issue?
call  uploadStreamToBlockBlob with arguments: 
Aborter.timeout(FIVE_MINUTES_IN_MS), readableStream, blockBlobURL, 4 * 1024 * 1024, 20

### Have you found a mitigation/solution?
Nope

**Comment by XiaoningLiu** [comment]
Hi @jakubzloczewski 

The `REQUEST_ABORTED_ERROR` error will be thrown when the `Aborter` timeouts. Seems you set a 5 mins timeout aborter. Can you remove the aborter and try again? If it works, it means the timeout value is not enough for the blob you tried to upload.

**Comment by jakubzloczewski** [comment]
Cool I will try with Aborte.none. Just for your information I'm uploading buffer which after save takes ~28 KB on disk.

**Comment by jakubzloczewski** [comment]
With `Aborter.none` it works perfectly fine.

**Comment by XiaoningLiu** [comment]
Good to see it works. But it unusual about uploading a 28KB file takes more than 5mins.
