### ISSUE TITLE
Can't set file Content-MD5

### ISSUE THREAD

**Issue by victor-accarini** [Azure/azure-storage-js#40]
### Which service(blob, file, queue, table) does this issue concern?
File

### Which version of the SDK was used?
10.0.0

### What's the Node.js/Browser version?
Firefox 63

### What problem was encountered?
Can't set Content-MD5 in file, it stays equals "-" on Azure.

![image](https://user-images.githubusercontent.com/5943663/49897040-265e3080-fe3c-11e8-811f-7b4310078181.png)

### Steps to reproduce the issue?
just call 
``` js
uploadBrowserDataToAzureFile(
  aborter,
  file,
  fileURL,
  {
    fileHTTPHeaders: {
      fileContentMD5: new Uint8Array("any MD5 hash")
    }
  });
```

### Have you found a mitigation/solution?
Tried using setHTTPHeaders after uploading the file. Same problem.

**Comment by XiaoningLiu** [comment]
Hi @victor-accarini 

You cannot initialize a Uint8Array with a MD5 hash string directly. Try with this way. Or use some helper methods to transfer a MD5 hash string into Uint8Array.

```javascript
      contentMD5: new Uint8Array([
        0x8b,
        0x1a,
        0x99,
        0x53,
        0xc4,
        0x61,
        0x12,
        0x96,
        0xa8,
        0x27,
        0xab,
        0xf8,
        0xc4,
        0x78,
        0x04,
        0xd7
      ])
    });
```

**Comment by victor-accarini** [comment]
Thanks! My mistake! Now it's working.
