### ISSUE TITLE
Update dependencies - remove deprecated ms-rest-js and instead use @azure/ms-rest-js

### ISSUE THREAD

**Issue by tbarlow12** [Azure/azure-storage-js#43]
### Which service(blob, file, queue, table) does this issue concern?
All

### Which version of the SDK was used?
10.2.0-preview

### What's the Node.js/Browser version?
Both

### What problem was encountered?
ms-rest-js is [deprecated](https://www.npmjs.com/package/ms-rest-js) and moved [here](https://github.com/Microsoft/VoTT/tree/tbarlow12/azure-blob-storage)

**Comment by XiaoningLiu** [comment]
Will update to @azure/ms-rest-js in next release :)

**Comment by tbarlow12** [comment]
Thank you @XiaoningLiu!
