### ISSUE TITLE
How to upload a local file from browser?

### ISSUE THREAD

**Issue by varghesep** [Azure/azure-storage-js#48]
The [BlobService ](https://azure.github.io/azure-storage-node/BlobService.html) has a method called ```createBlockBlobFromBrowserFile``` to upload a HTML5 ```File``` Object to the Blob storage. I can't find a similar call to upload the HTML5 ```File``` object. Is there one?

I'm also confused by different APIs available to upload stream to Blob storage. There is Azure BlobService, Azure Storage SDK 2.1 and now 10.1. Can I still use Blobservice or is it deprecated?

**Comment by XiaoningLiu** [comment]
@varghesep 

V10 is next generation of Azure Storage JavaScript SDK. It has new architecture and design, more compatibility and lightweight. You can continue to use V2, or considering moving to V10.

For V2, only way to use the browser version is to load the JS bundle. While for V10, you can directly import the @azure/storage-blob npm package.

In V2, `createBlockBlobFromBrowserFile` only accepts `File`. While for V10, `uploadBrowserDataToBlockBlob` accepts `Blob | ArrayBuffer | ArrayBufferView`. `File` inherits from `Blob`, so it accepts `File` too. 

https://docs.microsoft.com/en-us/javascript/api/%40azure/storage-blob/index?view=azure-node-preview#uploadbrowserdatatoblockblob-aborter--blob---arraybuffer---arraybufferview--blockbloburl--iuploadtoblockbloboptions-

**Comment by XiaoningLiu** [comment]
You can create a ServiceURL by:

const pipeline = StorageURL.newPipeline(new AnonymousCredential());
new ServiceURL(“https://account.blob.core.windows.net?SAS_TOKEN”, pipeline);

Best,
Xiaoning

**Comment by raufdean** [comment]
Implemented both the V2 & V10 methods as above. Over a slow patchy wifi connection the V10 method failed repeatedly. The V2 method was however very reliable. Would you have any idea why this might be the case ?

**Comment by XiaoningLiu** [comment]
@raufdean 

Can you share the parameters you have used? Such as file size, blockSize, parallelism/concurrency, retry settings and etc.

Error messages printed by V10 are also very helpful.

V10 enables retry policy by default, while V2 not. It's interesting V2 is more reliable on your side.

**Comment by raufdean** [comment]
@XiaoningLiu Sure. So small files were ok, but anything over 20Mb seemed to be a problem (this was a very unreliable connection). The upload would progress, and then fail right at the end. I tried with paralleism set to 1, and reduced blocksize to 1024 x 512 but still had the same problem. The error was always a ERR_CONNECTION_RESET from Azure. I have some HAR files that I can send you directly. I then used your V2 code above, and the uploads of the same files over the same connection were fine

**Comment by XiaoningLiu** [comment]
@raufdean If file size less than `maxSingleShotSize` (default is 256MB in bytes), file will be uploaded via a single http request. So besides setting `blocksize` to 1024 x 512, you need to set a small `maxSingleShotSize` such as `1024 * 512` to make the `blocksize` work. Have a try.

Please share the HAR files. What I can do is to make retry policy work for that kind of errors.

**Comment by XiaoningLiu** [comment]
Will close this issue as long time no response, fell free to re-open if you have further questions.

**Comment by zuo305** [comment]
iPad video not support.
throw new Error(objectName + " must be a string, Blob, ArrayBuffer, ArrayBufferView, or a function returning NodeJS.ReadableStream.");
