### ISSUE TITLE
@Azure/storage-queue is causing builds to fail in Create React App Typescript

### ISSUE THREAD

**Issue by Rocinante89** [Azure/azure-storage-js#52]
### Which service(blob, file, queue, table) does this issue concern?

queue

### Which version of the SDK was used?

@azure/storage-queue@10.0.0-preview

### What's the Node.js/Browser version?

Node.js v10.14.1

### What problem was encountered?

When attempting to run CRA-ts with the above version installed I get this error: 

./node_modules/@azure/storage-queue/dist-esm/lib/index.browser.js
Module not found: [CaseSensitivePathsPlugin] `/app/node_modules/@azure/storage-queue/dist-esm/lib/MessageIdURL.js` does not match the corresponding path on disk `MessageIDURL.js`.

### Steps to reproduce the issue?

 - Have latest versions of Create React App Typescript and @azure/storage-queue in package.json
- Run npm start

### Have you found a mitigation/solution?

Renaming MessageIDURL.js to MessageIdURL.js fixes the issue

**Comment by jiacfan** [comment]
Hi, @Rocinante89 

Thanks for reaching us and report the issue! 
This issue has been fixed in [PR](https://github.com/Azure/azure-storage-js/pull/49/files), and will be released this month. I'll update status in this issue when it's released.

Best Regards,
Jiachen

**Comment by jiacfan** [comment]
At same time, appreciate other suggestions and welcome discussion.

Thanks,
Jiachen
