### ISSUE TITLE
replace sas token while uploading to blob storage

### ISSUE THREAD

**Issue by mrcnw** [Azure/azure-storage-js#58]
### Which service(blob, file, queue, table) does this issue concern?
Blob
### Which version of the SDK was used?
lastest
### What's the Node.js/Browser version?
chrome
### What problem was encountered?
Is there any possibility to replace SAS_TOKEN while uploading to Blob Storage? Below I will describe exactly the problem.

Example:
Our expire time of token is 24 min. I would like to upload 10GB file and it will take about 1 hour with my network connection. After 24 min upload fails with response 401 (auth issues) - token expired. Is there any possibility to replace after 23 min of uploading with new valid sas token? It is just the question, ofc we could extend the lifetime of token to 1hr or 2hrs, but I would like not to do that.

23 mins with token A
23 - 46 mins with token B
etc.

### Steps to reproduce the issue?
-
### Have you found a mitigation/solution?
no

**Comment by emilwaw** [comment]
+1
Looking for the same solution = dynamic prolongation of SAS token validity when a big file is being uploaded

**Comment by XiaoningLiu** [comment]
@mrcnw @emilwaw I created a wiki to show how to implement SAS injection.

https://github.com/Azure/azure-storage-js/wiki/Customize-HTTP-Pipeline-and-Policies-to-Dynamic-Inject-SAS-During-a-Uploading
