### ISSUE TITLE
high-level samples Abort.timeout duration

### ISSUE THREAD

**Issue by Apollinaire** [Azure/azure-storage-js#65]
### Which service(blob, file, queue, table) does this issue concern?

Documentation samples

### Which version of the SDK was used?

Irrelevant

### What's the Node.js/Browser version?

Irrelevant

### What problem was encountered?

The timeout duration in the sample examples appears to be wrong: 
`30 * 60 * 60 * 1000` is 30 hours, not 30 mins as the comment says. It should be `30 * 60 * 1000` to avoid leading unattentive devs (does that even exist?) to have their timeout duration a bit too big.

### Steps to reproduce the issue?

Irrelevant

### Have you found a mitigation/solution?

The time calculation should be `30 * 60 * 1000` at the following places : 

https://github.com/Azure/azure-storage-js/blob/master/blob/samples/highlevel.sample.js#L60-L87

https://github.com/Azure/azure-storage-js/blob/master/blob/samples/highlevel.sample.js#L87

https://github.com/Azure/azure-storage-js/blob/master/file/samples/highlevel.sample.js#L67

https://github.com/Azure/azure-storage-js/blob/master/file/samples/highlevel.sample.js#L94

**Comment by XiaoningLiu** [comment]
Thanks for reporting! We will fix, at the same time. PR is welcome.

**Comment by XiaoningLiu** [comment]
This is fixed in latest releases from 10.4.0, see https://www.npmjs.com/package/@azure/storage-blob
