### ISSUE TITLE
Missing setProperties function for blob

### ISSUE THREAD

**Issue by compulim** [Azure/azure-storage-js#68]
### Which service(blob, file, queue, table) does this issue concern?

blob

### Which version of the SDK was used?

`10.3.0`

### What's the Node.js/Browser version?

`11.9.0`

### What problem was encountered?

Missing `setProperties` on `BlobURL`. There are `getProperties` and `setMetadata` though.

### Steps to reproduce the issue?

N/A

### Have you found a mitigation/solution?

No

**Comment by XiaoningLiu** [comment]
See `setHTTPHeaders()`

**Comment by compulim** [comment]
It works, thanks.

```js
await blobURL.setHTTPHeaders(
  Aborter.none,
  {
    blobContentType: 'text/javascript; charset=utf-8'
  }
);
```
