### ISSUE TITLE
Support for Angular4 (Typescript < 2.4)

### ISSUE THREAD

**Issue by olivermchaleTU** [Azure/azure-storage-js#72]
### Which service(blob, file, queue, table) does this issue concern?

Blob (+ms-rest-js)

### Which version of the SDK was used?

10.0.3

### What's the Node.js/Browser version?

Angular 4 + dependencies (TypeScript 2.3.3)

### What problem was encountered?

The library is incompatible with Angular4. Angular4 must use TypeScript 2.3.3 which doesn't support String enum declaration which is done in 

- queryCollectionFormat.d.ts
- SASQueryParameters.d.ts

### Steps to reproduce the issue?

1. Use Angular4 or TypeScript 2.3.3

2. Npm install the latest version of this. 

3. Reference it i.e. import { } from '@azure/storage-blob';

4. You'll see an error 'In ambient enum declarations member initializer must be constant expression' aka no string enum delcaration allowed.

### Have you found a mitigation/solution?

Not a solution but I can fix this locally by making the above files' containing enums use numerical enums instead of strings to fix this, although I imagine this does break some functionality. 

... Or use the legacy SDK. Although that sort of defeats the purpose as Angular4 was <2 years ago

**Comment by XiaoningLiu** [comment]
@olivermchaleTU TypeScript 2.3.3 seems released almost 2 years ago. To make the SDK compatible with old version TypeScripts, the project's TypeScript future set will be locked.

I'm not an Angular expert, but curious why cannot upgrade the TypeScript version used?

**Comment by olivermchaleTU** [comment]
Angular 4 relies on certain versions of the typescript compiler per versions, for example if you try to upgrade to 2.4 (for string enum declaration) you get the following warning 

@angular/compiler-cli@4.4.3 requires typescript@'>=2.1.0 <2.4.0' but 2.5.2 was found instead.
Using this version can result in undefined behaviour and difficult to debug problems.

Please run the following command to install a compatible version of TypeScript.
    npm install typescript@'>=2.1.0 <2.4.0'

I have tried upping the version anyway but that causes a lot of buggy (broken) functionality across our front-end packages when dealing with promises, and even causes a bunch of compile issues so unfortunately that isn't an option

**Comment by XiaoningLiu** [comment]
Hi @olivermchaleTU Thanks for explaining? Seems you are trying with typescript 2.5.2 with bugs. How about typescript 2.4.0? Or is able to update angular-cli to a newer version accepting typescript@2.4.0?

I'm sorry that it's difficulty for the SDK to drop string enum within a minor change, as it's potentially breaking.  

The right way I think is to update the Angular version. If you stay on the legacy Angular version, you need to make sure all the dependency modules stay on the legacy TS grammars. As the time goes on, it will become more difficult.

**Comment by olivermchaleTU** [comment]
Sorry - that error message was one just a generic one I took as I wasn't at my PC.  @XiaoningLiu  - my TS version is actually 2.3.3 

That's understandable and makes sense, as I know the refactor could break a load of stuff. The problem with upgrading the Angular version is the impact would be large as the project is huge. 

I do think the best solution at the moment is to upgrade the Angular version though. Another temporary thing for me is to fork the repo's (this+ms-rest-js) with my own changes in then publish that to npm to consume.

Thanks for your time 👍
