### ISSUE TITLE
how to handle viewing files that are stored in azure storage with multiple mime types

### ISSUE THREAD

**Issue by dagda1** [Azure/azure-storage-js#73]
### Which service(blob, file, queue, table) does this issue concern?

blob

### Which version of the SDK was used?

10.0.3

### What's the Node.js/Browser version?

8.11.1

### What problem was encountered?

I have an angular app that displays a table of records and each record has a link to a file store in azure storage.

Once the user clicks on a link, it executes this code:

```
  async downloadFile(file: UploadedFileMetaData) {
    if (this.downloading.has(file)) {
      return;
    }

    this.downloading.add(file);

    let url: string;

    try {
      url = await this.blobStorageService.getDownloadUrl(file);
    } catch (err) {
      throw err;
    }

    return this.http
      .get(url, {
        responseType: ResponseContentType.Blob
      })
      .map((res) => {
        return {
          filename: file.blobName,
          data: res.blob()
        };
      })
      .subscribe(
        (res) => {
          console.log('start download:', res);
          const fileUrl = window.URL.createObjectURL(res.data);
          const a = document.createElement('a');
          document.body.appendChild(a);

          a.setAttribute('style', 'display: none');

          a.href = fileUrl;

          a.download = res.filename;
          a.click();

          window.URL.revokeObjectURL(fileUrl);
          a.remove();
        },
        (error) => {
          this.downloading.delete(file);
          console.log('download error:', JSON.stringify(error));
        },
        () => {
          this.downloading.delete(file);
          console.log('Completed file download.');
        }
      );
  }
```
Is there anyway I can get these files to open in the browser this way. Downloading the files to the user's hard drive is not a great experience and does not seem to work on iphone or ipad.

**Comment by dagda1** [comment]
Does anyone have any suggestions for this?

**Comment by XiaoningLiu** [comment]
Hi @dagda1 Did you use @azure/storage-blob? 

To download blob into browser's memory instead of local disk, you can call `BlobURL.download()` to get Azure Storage blob data into a [Web API Blob](https://developer.mozilla.org/en-US/docs/Web/API/Blob)
```javascript
const response = await BlobURL.download(Aborter.timeout(20 * 60 * 1000), 0);
const data = await response.blobBody; // data is the data you needed 
```

**Comment by dagda1** [comment]
@XiaoningLiu will this work for large files?

**Comment by XiaoningLiu** [comment]
Depends on browser's memory limitation. Not recommend to handle large files inside browser's memory.

**Comment by dagda1** [comment]
how about video, do you have any guidance for how I could handle streaming video from azure?

**Comment by XiaoningLiu** [comment]
You may want to have a look at Azure Media Service which based on blob storage and provides a player

https://azure.microsoft.com/en-us/services/media-services/
https://azure.microsoft.com/en-us/solutions/architecture/digital-media-video/

**Comment by XiaoningLiu** [comment]
Will close this issue as this is not a storage SDK issue, fell free to re-open if you have further questions.
