### ISSUE TITLE
Cannot find name 'Event'

### ISSUE THREAD

**Issue by fela98** [Azure/azure-storage-js#75]
### Which service(blob, file, queue, table) does this issue concern?
Encountered on blob, but I would guess it concerns more of them.

### Which version of the SDK was used?
10.3.0

### What's the Node.js/Browser version?
NodeJS v10.14.1

### What problem was encountered?
Getting a typescript error that the type 'Event' was not found. If I enable "dom" lib in my tsconfig.json, I can compile without any problems.

### Steps to reproduce the issue?
Clone repo and use typescript without the "dom" lib option. I used typescript v3.2.1
![image](https://user-images.githubusercontent.com/6069003/53234095-114d1b80-368f-11e9-8efd-774ace39a1ec.png)

### Have you found a mitigation/solution?
Workaround is to add "dom" to lib in tsconfig, when in a NodeJS environment this is not optimal however because I would get lots of types and functions available in typescript which may fail at run-time because the DOM is not really available at run-time in NodeJS.

**Comment by XiaoningLiu** [comment]
Thanks for reporting! For Aborter implementation, seems `any` is better than `Event` type.

For this SDK, `dom` is needed because it needs to handle both Node.js and browser runtime features.

**Comment by kellermanrivero** [comment]
I have the same issue. Any plan to fix this issue?

**Comment by XiaoningLiu** [comment]
Yes. Before that, please include "dom" in your tsconfig "lib".

**Comment by ashapir0** [comment]
If possible, please add this to some sort of FAQ, rather frustrating and in-descript error.

**Comment by XiaoningLiu** [comment]
Will do.

**Comment by roppa** [comment]
I'm getting this error too. To be completely explicit about the `tsconfig.json` fix:
```
{
  "compilerOptions": {
    "lib": [
      "dom"
    ]
}
```

**Comment by drub0y** [comment]
Is it safe to assume this going to be sorted out in a future release? Having to reference `dom` in a node app that otherwise has no need for it is not exactly intuitive and, once you do, it just leads to a ton of types showing up in the global space that have no other reason to be there.

**Comment by XiaoningLiu** [comment]
Fix will be included in the release of this month.

**Comment by XiaoningLiu** [comment]
This is fixed in 10.4.0, see https://www.npmjs.com/package/@azure/storage-blob
