### ISSUE TITLE
Gracefully handle 404 of reading from blob

### ISSUE THREAD

**Issue by tbarlow12** [Azure/azure-storage-js#77]
### Which service(blob, file, queue, table) does this issue concern?
Blob

### Which version of the SDK was used?
10.3.0

### What's the Node.js/Browser version?
Browser

### What problem was encountered?
Not being able to gracefully catch 404 when trying to read text from a non-existent blob

### Steps to reproduce the issue?
- Get a `blockBlobURL` object for a non-existent blob but an existing container
- Call `await blockBlobURL.download(Aborter.none, 0);` inside of a try catch
- The catch is reached, but the 404 error has already been thrown and cannot be prevented

### Have you found a mitigation/solution?
For now, we're reading all blobs from the container to check that the blob exists before trying to read from the blob, but that's not very performant

**Comment by XiaoningLiu** [comment]
Hi @tbarlow12

The exception is already caught and well handled by SDK. If you are referring to the red line error, this red line output is controlled by browsers to display network errors. You don't need to care about it. Or you can disable displaying network request errors from console.

![image](https://user-images.githubusercontent.com/6889160/53707160-c1c5d700-3e68-11e9-857c-1e22a496e982.png)

![image](https://user-images.githubusercontent.com/6889160/53707230-0ea9ad80-3e69-11e9-94c0-7ff928faa199.png)

**Comment by XiaoningLiu** [comment]
Will close this issue as this is not a SDK issue, fell free to re-open if you have further questions.
