### ISSUE TITLE
More documentation around ACCOUNT_SAS in contributing.md

### ISSUE THREAD

**Issue by bterlson** [Azure/azure-storage-js#8]
I can't get the browser tests to work and I suspect it's because I'm not setting ACCOUNT_SAS properly. Should it be a query string (the SAS Token field in portal after clicking "Generate SAS and connection string"?

**Comment by XiaoningLiu** [comment]
@bterlson Yes, but need to make sure the environment variable has been setup properly. If using Windows CMD, add quotes to escape the SAS.
```
set "ACCOUNT_SAS=?sas"
```

**Comment by bterlson** [comment]
Ahh I had a line break in my SAS token for some reason (possibly because I copy/pasted from portal?). Anyway I think it would be good to call out that the SAS Token is indeed a query string starting with `?sas`.

**Comment by XiaoningLiu** [comment]
I should make it more clear, sas is starting with "?", instead of "?sas"..

```
set "ACCOUNT_SAS=<SASTOKEN>"
```

**Comment by XiaoningLiu** [comment]
will add document about CORS into the document

**Comment by XiaoningLiu** [comment]
Resolved in release 10.1.0-preview, thanks!

**Comment by pungggi** [comment]
Not sure if it fits to this issue @XiaoningLiu  but do you have an example on how to generate sas with nodejs? I mean for using the browser for uploading i need to generate SAS on the fly not copy paste it right ;) So I need to call a Service lik getSAS()..

**Comment by XiaoningLiu** [comment]
@pungggi 

Yes, there are 2 global methods `generateAccountSASQueryParameters` and `generateBlobSASQueryParameters`, the 2 methods will return a `SASQueryParameters` object, then you can call `toString()` to get a SAS string.

And you can go to the source code or API reference for the parameter needed.
