### ISSUE TITLE
How to list blobs from virtual directory in latest nodejs SDK?

### ISSUE THREAD

**Issue by jeyarajcs** [Azure/azure-storage-js#85]
How to list blobs from virtual directory in latest nodejs SDK?
Example : 
              container_name/videos/May/02/myvideo.webm
              container_name/videos/May/02/myvideo1.webm
              container_name/videos/May/02/myvideo2.webm
              container_name/videos/May/02/myvideo3.webm

I need to get blob list from **container_name/videos/May/02/**

_Originally posted by @jeyarajcs in https://github.com/Azure/azure-storage-js/issues/19#issuecomment-488986976_

**Comment by XiaoningLiu** [comment]
@jeyarajcs Call `listBlobHierarchySegment()` and use `"container_name/videos/May/02/"` as the prefix.

**Comment by jeyarajcs** [comment]
Thank you so much. It's working.
